version: "3.0"

services:
  web:
    build: ./server
    restart: always
    tty: true
    volumes:
      - ./server/app:/app
    ports:
      - 8000:8000

  db:
    image: postgres:13.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: sample
      TZ: "Asia/Tokyo"
    hostname: postgres
    volumes:
      - ./db/initdb:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:5.0
    restart: always
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root@root.com
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    depends_on:
      - db
