version: "3.0"

services:
  web:
    build: ./server
    restart: always
    tty: true
    volumes:
      - ./server/app:/app
    environment:
      TZ: Asia/Tokyo
    ports:
      - 8000:8000

  db:
    build: ./db
    volumes:
      - ./db/save_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=danime
      - MYSQL_USER=test
      - MYSQL_PASSWORD=test
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Tokyo

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=root
    restart: always
    ports:
      - 3031:80
    depends_on:
      - db
