version: "3.0"

services:
  web:
    build: ./server
    container_name: d-anime-mylist-backend-web
    hostname: web-server
    restart: always
    tty: true
    volumes:
      - ./server/app:/app
    environment:
      TZ: "${TZ}"
      DB_USER_NAME: "${DB_USER_NAME}"
      DB_PW: "${DB_USER_PW}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
    expose:
      - 8000
    depends_on:
      - db
    networks:
      - d-anime-mylist-web
      - d-anime-mylist-db

  nginx:
    image: nginx:alpine
    container_name: d-anime-mylist-backend-nginx
    hostname: nginx-server
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - d-anime-mylist-web

  db:
    build: ./db
    container_name: d-anime-mylist-backend-db
    hostname: db-server
    volumes:
      - ./db/save_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER_NAME}"
      MYSQL_PASSWORD: "${DB_USER_PW}"
      MYSQL_ROOT_HOST: "%"
      TZ: "${TZ}"
    networks:
      - d-anime-mylist-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: d-anime-mylist-backend-phpmyadmin
    hostname: phpmyadmin-server
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: db
      PMA_USER: "${DB_USER_NAME}"
      PMA_PASSWORD: "${DB_USER_PW}"
    restart: always
    ports:
      - 3030:80
    depends_on:
      - db
    networks:
      - d-anime-mylist-db

networks:
  d-anime-mylist-web:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.10.0/24
  d-anime-mylist-db:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.20.0/24
