version: "3.0"

services:
  web:
    build: ./server
    restart: always
    tty: true
    volumes:
      - ./server/app:/app
    environment:
      TZ: "${TZ}"
      DB_USER_NAME: "${DB_USER_NAME}"
      DB_PW: "${DB_USER_PW}"
      DB_HOST: "${DB_HOST}"
      DB_NAME: "${DB_NAME}"
    expose:
      - 8000
    networks:
      - d-anime-mylist-web
      - d-anime-mylist-db

  nginx:
    image: nginx:alpine
    depends_on:
      - web
    ports:
      - 80:80
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    networks:
      - d-anime-mylist-web

  db:
    build: ./db
    volumes:
      - ./db/save_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PW}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USER_NAME}"
      MYSQL_PASSWORD: "${DB_USER_PW}"
      MYSQL_ROOT_HOST: "%"
      TZ: "${TZ}"
    networks:
      - d-anime-mylist-db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: "${DB_HOST}"
      PMA_USER: "${DB_USER_NAME}"
      PMA_PASSWORD: "${DB_USER_PW}"
    restart: always
    ports:
      - 3031:80
    depends_on:
      - db
    networks:
      - d-anime-mylist-db

networks:
  d-anime-mylist-web:
    driver: bridge
  d-anime-mylist-db:
    driver: bridge
